### ISSUE TITLE
chmod doesn't convert metaplex-token-metadata-test-client to executable on mac os

### ISSUE THREAD

**Issue by kc-hsh-value** [draffle-io/draffle#28]
even though i run chmod +x scripts/metaplex-token-metadata-test-client on terminal, i still get the following error when i try to start_dev.sh:

/Users/xxx/Desktop/moreRaffles/draffle/scripts/metaplex-token-metadata-test-client: cannot execute binary file

**Comment by moneytoad888** [comment]
> even though i run chmod +x scripts/metaplex-token-metadata-test-client on terminal, i still get the following error when i try to start_dev.sh:
> 
> /Users/xxx/Desktop/moreRaffles/draffle/scripts/metaplex-token-metadata-test-client: cannot execute binary file

You need to build the binary for mac, it is extremely annoying but unfortunately the binary isn't cross platform

**Comment by kc-hsh-value** [comment]
> You
ok thnx i fixed it

**Comment by pbredenberg** [comment]
Would someone mind sharing how to build the binary for mac? The docs say to run `cargo build --release` but this has no effect, still cannot execute metaplex-token-metadata-test-client on macOS for me

EDIT:

I realized what the docs meant was that you need to clone [metaplex-program-library](https://github.com/metaplex-foundation/metaplex-program-library), cd into the `token-metadata` directory, and within there run `cargo build --release`. The executable version will then be inside `token-metadata/target/release`.

Copy the new binary to `draffle/scripts/`.
